spring:
  data:
    redis:
      port: 6379
      host: localhost
      channel:
        follower: follower_channel
        achievement: achievement_channel
        profile-view: profile_view_channel
        comment: comment-event-channel
        like: like-event-channel
        publish_post: publish_post_channel

  mail:
    host: smtp.gmail.com
    port: 587
    username: manticorestream7@gmail.com #https://www.baeldung.com/spring-email
    password: uoeg leun kfyb umjz #генерируем для своего Google аккаунта по инструкции https://support.google.com/accounts/answer/185833
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  messages:
    basename: messages

server:
  port: 8083

logging:
  level:
    root: info

#Можно зарегистрировать аккаунт без привязки карты. Будет 2 евро на отправку тестовых SMS
vonage: #https://dashboard.nexmo.com/getting-started/sms
  api:
    key: whatever
    secret: whatever
    from: Manticore Notification Service

telegram:
  notification-bot:
    username: manticore_notification_bot
    token: 7431818496:AAGZygfW_KWSkRRqpmPXn2oy2WOUMn0jnt0
    retry:
      max-attempts: 4
      backoff-delay: 2000

project-service:
    host: localhost
    port: 8082
user-service:
    host: localhost
    port: 8080
    base-path: /api/v1

async:
  event-listener:
    corePoolSize: 5
    maxPoolSize: 30
    queueCapacity: 100